[package]
name = "dcd"
version = "0.1.0"
authors = ["peta <peta.maj82@gmail.com>"]
edition = "2018"

[lib]
name = "dcd"
path = "src/lib.rs"

[[bin]]
name = "dcd"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2="0.13"
csv="1.1"
serde = { version = "1", features = ["derive"] }
crossbeam="0.7"
curl="0.4"
json="0.12"
chrono="0.4"
bincode="1.3.1"
byteorder="1.3.4"
rand="0.7"
sha-1="0.9"
