[package]
name = "ghmrs"
version = "0.1.0"
authors = ["peta <peta.maj82@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2="0.13"
csv="1.1"
crossbeam="0.7"
curl="0.4"
json="0.12"
