[package]
name = "parasite"
version = "0.3.0"
authors = ["peta <peta.maj82@gmail.com>"]
edition = "2018"

[lib]
name = "parasite"
path = "src/lib.rs"

[[bin]]
name = "parasite"
path = "src/main.rs"

#[[bin]]
#name = "dcd-view"
#path = "src/dcd_view.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2="0.13"
csv="1.1"
crossbeam="0.7"
crossbeam-channel="0.5.0"
curl="0.4"
json="0.12"
chrono="0.4"
#bincode="1.3.1"
byteorder="1.3.4"
rand="0.7"
sha-1="0.9"
flate2="1.0"
num = "0.3"
num-derive = "0.3"
num-traits = "0.2"
# not this one, really, really bad dependencies
#sysinfo = "0.15.0"
lazy_static = "1.4.0"
